:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: imgs/

[.lead]
Pull requests are only for fixes. +
Dux is intended to be forked; maintain your own fork of Dux if you want to do beyond bug fixes.

=== Recommended tools
. https://github.com/koalaman/shellcheck | link:https://github.com/vscode-shellcheck/vscode-shellcheck[VS Code addon]
. https://github.com/mvdan/sh#shfmt | link:https://github.com/foxundermoon/vs-shell-format[VS Code addon]
. https://github.com/hangxingliu/vscode-systemd

.The old rules; no longer applies, but contains useful information if you plan to fork Dux.
[%collapsible]
====

[.lead]
These specific contributions won't be accepted, please make your own fork and be willing to give full support for it.

NOTE: The overall quality of Dux degrades when adding features/options that don't get daily use by the person that primarily added those features/options in the first place. +
You can expect higher quality from forking and doing this work yourself, since you know exactly why you want what you have added and how it should function, while I don't.

* Other Linux kernels, especially `linux-hardened` and `linux-zen`.
** `linux-zen` used to be Dux's default, but it caused some PCs to fail booting while `linux` and `linux-lts` wouldn't.

* Installers & uninstallers for other desktop environments, and any window manager setups.

* Option to disable Flatpaks.
** I would never test for this, that is the issue. Some Flatpaks are chosen on the basis that they function better than the Arch variant, and vice versa.

* Bootloaders with no support for Btrfs snapshots, such as `systemd-boot`.

* Alternative initramfs generators, such as Booster or Dracut.
** A lot can go wrong easily, in a similar way that changing Linux kernels could.

* UEFI secure boot support.

* Encrypted /boot support.

* Ricing oriented:
** Any GNOME plugins from the AUR.

====
